### ISSUE TITLE
Accomodate existing User models in OpenHumansMember.get_create_member()

### ISSUE THREAD

**Issue by oguzhanogreden** [OpenHumans/django-open-humans#15]
Hi,

As a user of the app who has his OwnUser model in another Django app, I would like to be able to use `OpenHumansMember.get_create_member()` to easily get/create OpenHumansMember object for _an instance of my OwnUser model_.

I think it may be enough to add a `user` argument to `.get_create_member()` and pass this along to `.create()`. With a `None` default, current functionality will remain intact.

I've been watching OpenHumans with joy, loads of thanks for your work! 👍 
Oguzhan

**Comment by madprime** [comment]
This sounds like something we should add!

Yes, it looks like `user` could be passed to `get_create_member` and used when `create` is called.

And the `user` parameter would only get used by `get_create_member` for when a new member is being created. If an existing one matches, `get_create_member` would return that match, which might have a difference user (and the `user` parameter wouldn't be used for anything).

**Comment by gedankenstuecke** [comment]
Yep, that sounds good to me. So only two things would need to be changed to achieve this behaviour: 

- [ ] add the `user` parameter with default to `None` to `get_create_member()` function [here](https://github.com/OpenHumans/django-open-humans/blob/master/openhumans/models.py#L93). 
- [ ] pass that parameter to the 'regular' `create` function inside `get_create_member` function [here](https://github.com/OpenHumans/django-open-humans/blob/master/openhumans/models.py#L109).

@oguzhanogreden Do you want to make those changes and submit a pull request to add those? Because it looks like this could be a great first contribution! 🙂

**Comment by madprime** [comment]
Closed by #16
